#
# Makefile for the phy drivers.
#

obj-$(CONFIG_GENERIC_PHY)		+= phy-core.o
obj-$(CONFIG_PHY_EXYNOS_MIPI_VIDEO)	+= phy-exynos-mipi-video.o
obj-$(CONFIG_PHY_MVEBU_SATA)		+= phy-mvebu-sata.o
obj-$(CONFIG_PHY_MSM_SATA)		+= phy-msm-sata.o
obj-$(CONFIG_SCSI_UFS_QCOM) 		+= phy-qcom-ufs.o
obj-$(CONFIG_SCSI_UFS_QCOM) 		+= phy-qcom-ufs-qmp-28nm.o
obj-$(CONFIG_SCSI_UFS_QCOM) 		+= phy-qcom-ufs-qmp-20nm.o
